name: firebase_deep_link_client
description: A Dart package which provides a deep link stream
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  deep_link_client:
    path: ../deep_link_client
  equatable: ^2.0.8
  firebase_core: ^3.15.2
  firebase_dynamic_links: ^6.1.10
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  firebase_core_platform_interface: ^6.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
