name: news_blocks
description: Reusable News Blocks for the Flutter News Example Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  equatable: ^2.0.8
  json_annotation: ^4.9.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.13.0
  coverage: ^1.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.30.0
  very_good_analysis: ^10.2.0
