name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^5.7.0
  firebase_auth_platform_interface: ^7.7.3
  firebase_core: ^3.15.2
  firebase_core_platform_interface: ^6.0.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.5
  google_sign_in: ^6.3.0
  plugin_platform_interface: ^2.1.8
  sign_in_with_apple: ^7.0.1
  token_storage:
    path: ../token_storage
  twitter_login: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
